### ISSUE TITLE
Coord Formats: MapTiles

### ISSUE THREAD

**Issue by tebarius** [S-Man42/GCWizard#126]
Adding support for converting Coords to/from Maptiles would be nice.
code-examples for converting could be find here:  https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames

**Comment by S-Man42** [comment]
I've thought about it several times. I am not lucky with the z component. So if you wanted to convert LatLon to MapTiles you would add the information into which Z layer you are converting. So you need to add a second output parameter next the the format dropdown. I don't like this idea... 

Otherwise it could be used for GaußKrüger as well... 

Do you have a nice idea to solve this problem?

**Comment by tebarius** [comment]
In my own little python "mystery helper" I let the function output all zoom levels from 1-30 when converting from DEC to maptiles. When converting from maptile to DEC and DEG I let the function test all zoom levels from 1-30 and only the valid coordinates. I don't know if a similar approach is possible here.

**Comment by S-Man42** [comment]
Working on it. :)

**Comment by S-Man42** [comment]
Done in https://github.com/S-Man42/GCWizard/commit/78b509cf8672d611ff7480ab0dabe614178c40fc
