### ISSUE TITLE
Space Invaders: "bad"/unsymmetric symbols 

### ISSUE THREAD

**Issue by radlerandi** [S-Man42/GCWizard#127]
i guess the Space Invaders are taken from https://www.geocachingtoolbox.com/index.php?lang=de&page=codeTables&id=spaceInvadersAlphabet
I had 2 mysteries with Space Invaders code in the past days, and both of them use a more clearer and symmetric version of them for the riddle, one of caches is https://coord.info/GC8Q52F
Especially the numbers 3, 5 and 7 are difficult to differentiate. 

There are versions of Space Invaders with correct symmetry. I will provide a new set for them (after reading the blog post)

Also my screen is completely full of symbols and i can't hit Space or Back button. Because the numbers are on top and the buttons are below. Would have to scroll all the time, or enter only the complete code first and scroll then down.
![photo_2020-07-04_17-54-26](https://user-images.githubusercontent.com/6453989/86516271-6e2e1980-be1f-11ea-9def-d4e9f7656189.jpg)

**Comment by S-Man42** [comment]
Unless there's no better graphic set available (cannot take it from kryptografie.de!), we cannot do anything.

For optimizing the screen: Please change the settings: "Number of symbols shown in portrait mode" The more symbols you show in one row, the smaller is the whole screen. Otherwise you need to scroll.
