### ISSUE TITLE
Add Jigidi Solver

### ISSUE THREAD

**Issue by Birdy2404** [S-Man42/GCWizard#1406]
Would be great to have a jigidi solver, even I know, that some of the known solutons are blocked time by time.

https://gist.github.com/Dan-Q/e9bfe5c2ca4b13fae4994c5e84685761#file-jigidi-helper-js

**Comment by S-Man42** [comment]
I tend to say "won' t do". 

1. Jigidi regularly changes its code to avoid automatic solvers. So we'd be forced to constantly change ours too to keep this tool running. I peraonally don't want to do this.
2. Jigidi itself begged that we don't should use their platform for Geocaching. They clearly stated that they have enormous increased costs through that.
3. Furthermore they said that using the solvers are not wanted (that's why they try to outrun them). They kindly asked the Geocachers to simply not do the Mysteries if they don't like them.

So for these completely valid reasons, I don't want to support this crazy shit of Mysteries. I fully understand that the a free platform gets problems due to these. I want to respect they wish to not use solvers. And I don't want to support these Mysteries which are kind of a plaque. The fewer these Jigsaws want to solve, the more we help the Jigidi platform and the less Mysteries of that kind would be published.
