### ISSUE TITLE
Wedding anniversaries

### ISSUE THREAD

**Issue by Birdy2404** [S-Man42/GCWizard#1527]
https://www.welt-der-zahlen.info/hochzeitstage.html
Incl. searchfield like "Porzellan" will show 9 and 20 years
Problem could be the regional differences especially with 6 1/4; 12 1/2; ...
https://de.wikipedia.org/wiki/Hochzeitstag
https://en.wikipedia.org/wiki/Wedding_anniversary
https://es.wikipedia.org/wiki/Aniversario_de_bodas

**Comment by olliklee** [comment]
I'm working on a json file for that. For now are following languages  integrated:  EN/GB, EN/US, DE, NL, SW, DK, IT, ES, FR.
It's not working with crowdin, because of partially completely different representing words for different years.
Any wishes for more languages?
How shall the tool look and which category? Maybe like Zodiac Signs in Miscellaneous Tools?

**Comment by S-Man42** [comment]
I would keep it more simple like IP Schutzklassen

**Comment by olliklee** [comment]
This issue can be closed, i think.
