### ISSUE TITLE
Feature request: Add .apk builds to the Releases page for Obtainium users and people who wish not to use the Play Store

### ISSUE THREAD

**Issue by ElonSatoshi** [S-Man42/GCWizard#1552]

**Comment by S-Man42** [comment]
Hi, we absolutely understand this request. Sdding the apk to alternative stores is generally a good idea. However, we decided not to do this atm, because we cannot efford this. We are only a very small team and releasing is a huge act. Supporting more platforms would mean more time for the release procedure which we simply do not want to invest.

But it is a community project. If you like to help us, please feel free. We would be very happy.

**Comment by ElonSatoshi** [comment]
How much does it cost exactly to put a .apk in the Releases page on Github?

**Comment by t-m-z** [comment]
It is not a question of money but of time. Hence it would be fantastic if you could have a look at it
