### ISSUE TITLE
Suggestion to improve performance find numbers (Number Sequences)

### ISSUE THREAD

**Issue by Linsty** [S-Man42/GCWizard#1822]
Hi

Some functions take a long time to open (Android: App + Web) + Windows (Web). 

I suspect this is because:

- the default 0 is not in the sequence;
-  the sequence is likely large;
- GCW starts calculating immediately. 

I think you could significantly improve performance by adding a submit button so that users have time to enter the value first. 
(Similar to the Find Numbers and Index of Range functions). Could this be an easy fix?

Examples: Bell's number, Lucas sequence, Pell-Lucas sequence

Kind regards 

Marcia

**Comment by S-Man42** [comment]
I can reproduce it and confirm the supections. @t-m-z maybe the button could make sense.

Alternatively the search routine is too slow. So, if all tools open with 0, the check should come instantly (of course only for constantly increasing sequences, otherwise one does not not whether the 0 could come sometimes later...)

**Comment by t-m-z** [comment]
It is a mixture:
- an additional button 
- avoid infinite looping
- change to async


Sent from MailDroid

-----Original Message-----
