### ISSUE TITLE
Hidden data tries to play non-sound files

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#1883]
Try to load: s-man42.de/ahoy.png

I guess, the PNG accidentially contains some hex byte strings which equal magic bytes of a sound file. Here they may be chunked and tried to be played. 

If no sound can be played, it should be catched not repeated many times (many many error logs in emulator!)

**Comment by Mike-3** [comment]
I cannot find any hidden data in this file in either the emulator or the web version

**Comment by S-Man42** [comment]
there is none!

But the tool. is trying to find one, that's exactly the problem. Have a look at the log after loading the file.

**Comment by Mike-3** [comment]
OK, I can understand it now. The error message comes because magic bytes were found for a sound file. Then a test is carried out to see if it is a valid sound file. The test is carried out with the AudioPlayer lib and causes these messages. No attempt is made to play the file. The test is also caught with try catch. I have no idea how else you could test for a valid sound file. Or we ignore all sound formats.
But as I said. The messages only appear in the emulator and otherwise have no side effects.

**Comment by S-Man42** [comment]
yes, thats what I guessed... some random bytes which may indicate sound files...

however... do you know why there are that many attemps? (that many messages/loops)?

**Comment by Mike-3** [comment]
The "problem" in this case is that the MP3 magic bytes "0xFF, 0xFA" occur quite often. And since the MP3 magic bytes are only 2 bytes long, it is likely that the combination occurs very often in general.

**Comment by S-Man42** [comment]
ok, if you think, it's ok close it.
