### ISSUE TITLE
Visual Cryptography: Pixel Size

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#1932]
1x1 pixel is hard to print (example... "Folien"). I would love to see the same option as in QR code generator to be able maybe 3x3 or 5x5 grid for bigger printable pixels

**Comment by Mike-3** [comment]
I have a small problem. Because of the Pixel Size parameter, the parameters for decoding are different than for encoding if Pixel size > 0. The decoder does not know the Pixel size.

![encode](https://github.com/user-attachments/assets/f29df56d-6326-4369-9183-eda6fe949d1b)
encode

![decode](https://github.com/user-attachments/assets/be17684c-cbd8-400c-be98-74211c4fd53d)
decode

**Comment by Mike-3** [comment]
At most you try to determine the pixel size (block size). I have something like that in Piet.

**Comment by Mike-3** [comment]
But that works. But with pixel size 2, the offset is twice as large as specified for encrypt.
You actually expect that with the settings you used for encrypt, you will get the original again when you decrypt with the same settings. You just specify pixels for the offset (decrypt).
Well, I fell for it at first.

**Comment by Mike-3** [comment]
Again, the pixel/block size is not the problem. This worked before with different sizes.
Only the offsets are different when encrypting and then decrypting if an offset != 0 is used.
It's all about the offsets!!

**Comment by Mike-3** [comment]
I'm having trouble determining the block size. I have a list of "all" existing sizes (black and white). I'll just take the most common occurrence.

Test examples:
Map <size, number>
{4: 142, 6: 60, 2: 374, 8: 30, 10: 6, 12: 6} - > MapEntry(2: 374)
{3: 56, 1: 347, 2: 156, 4: 32, 6: 5, 5: 9} - > MapEntry(1: 347)
{4: 163, 2: 357, 6: 59, 8: 22, 10: 11, 14: 1, 16: 1, 12: 2} - > MapEntry(2: 357)

But I'm open to other suggestions.
I wanted to take the shortest length first. But if a pixel is missing somewhere, you end up with block size 1 instead of block size 2.
