### ISSUE TITLE
Navajo: Few thoughts

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#1938]
1. Translated dictionary? So if you want to code a German text? Currently it is not even clear that a German text is not available and you need to write it in English (furthermore, umlauts are not allowed in input field)
2. Simply show the dictionary as a list, so one can see which words are included

What do you think @t-m-z

**Comment by t-m-z** [comment]
Hm. 
1. It is an option. But I wouldn't add it to Crowdin. The translaters will hate us.
https://www.history.navy.mil/research/library/online-reading-room/title-list-alphabetically/n/navajo-code-talker-dictionary.html

2. I do not understand this point. I relied on the above link.

3. Valid point to add another tool - Navajo Code book - and a selection 

Sent from MailDroid

-----Original Message-----
From: MLorenz42 ***@***.***>
To: S-Man42/GCWizard ***@***.***>
Cc: Thomas ***@***.***>, Mention ***@***.***>
Sent: Mi., 02 Okt. 2024 10:40
Subject: [S-Man42/GCWizard] Navajo: Few thoughts (Issue #1938)

1. Translated dictionary? So if you want to code a German text? Currently it is not even clear that a German text is not available and you need to write it in English (furthermore, umlauts are not allowed in input field)
2. Since the code words are not the 1:1 translations (I watched "Windtalkers" where the code words for Tank was indeed the Navajo word for Tortoise), it could make sense to add the real translations or at least say: Bla-Blubb was used for ABC, but its real meaning was XYZ
3. Simply show the dictionary as a list, so one can see which words are included

What do you think @t-m-z 

-- 
Reply to this email directly or view it on GitHub:
https://github.com/S-Man42/GCWizard/issues/1938
