### ISSUE TITLE
Buggy Help Links

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#388]
* coords_selection_online_help_url is empty in EN (i guess there are some more...)
* Symboltables help link points to PDF download, not to help EN

**Comment by t-m-z** [comment]
regarding "coords_selection_online_help_url is empty in EN (i guess there are some more...)"
online_help_url checked and missing urls are added

regarding "Symboltables help link points to PDF download, not to help EN"
I do not understand because all links seems to be okay:
- "symboltables_selection_online_help_url" : "https://blog.gcwizard.net/manual/en/symboltables/01-which-symbol-tables-are-available/",
- "symboltables_selection_download_link" : "https://misc.gcwizard.net/symboltables_en.pdf",
- "symboltables_selection_online_help_url" : "https://blog.gcwizard.net/manual/de/symboltabellen/01-welche-symboltabellen-stehen-zur-verfugung/",
- "symboltables_selection_download_link" : "https://misc.gcwizard.net/symboltables_de.pdf",
