### ISSUE TITLE
RSA change buttons to radiobutton

### ISSUE THREAD

**Issue by Birdy2404** [S-Man42/GCWizard#490]
![grafik](https://user-images.githubusercontent.com/34218281/115136906-2a5d7700-a023-11eb-842d-3c86c113d434.png)
![grafik](https://user-images.githubusercontent.com/34218281/115136912-36493900-a023-11eb-801b-0092f756cc78.png)

**Comment by Birdy2404** [comment]
Got a second topic:
![grafik](https://user-images.githubusercontent.com/34218281/115137158-b1f7b580-a024-11eb-9127-4cf13396bbc0.png)
The Calculation button is not necessary, because the calculation starts automatic after filling the field with valid nubers

**Comment by S-Man42** [comment]
Nice catch... I know there was a reasons for the buttons, but I cant remember anymore. I will have a look

**Comment by Mike-3** [comment]
![grafik](https://user-images.githubusercontent.com/70719484/115259140-e73df980-a131-11eb-8977-edefcb093181.png)

ok ?

**Comment by S-Man42** [comment]
Yes, ok

**Comment by Birdy2404** [comment]
Looks, please switch the label to "manual", if I can get it on the virtual device

**Comment by S-Man42** [comment]
hm, which label?

**Comment by Birdy2404** [comment]
![grafik](https://user-images.githubusercontent.com/34218281/115420848-c5a94480-a1fb-11eb-8940-feeee66b78eb.png)
The Ticket-label ;-)

**Comment by S-Man42** [comment]
Hm, now I know, why I did it the way with two buttons:
1.) Now you have a potential click more: Click the switch and than click the button
2.) Less space is required: Only the button bar (= 1 row) vs button + Switch (= 2 rows)

What do you think? Stay convenient with the rest of the app (in that case, the entire GCWEncryptButtonBar can be removed from the code since it seems not to be use anywhere else) or spare clicks and space...

Currently I'd tend to the new version, but... The mentioned reasons are good as well? What do you think?

**Comment by Birdy2404** [comment]
Is the Calculation-Button really necessary, or can it be calculated directly.
If something is missing, we need to throw a helpful error message for the user, like "Prime number p is missing"

**Comment by Mike-3** [comment]
We can make this without the calculation button, but you then always have an error message until all fields have been filled out correctly. You can perhaps suppress the message as long as all fields are empty, so that an error is not displayed when you open it.

**Comment by Mike-3** [comment]
I would want to remove the GCWEncryptButtonBar, because it is really only used here and maybe really try without buttons.

**Comment by S-Man42** [comment]
@Mike-3 : Ok, could you commit the removement?

@Birdy2404: No. It makes no sense here. Because, as Mike said, you would get only messages until you finished your input. The function is not as the most other function, which can handle any arbitrary input. Here you need very specific values to get this working. Empty entries cannot be handled and even the most number would yield errors, as they are not prime numbers. So, even if you'd try to enter "997" as prime, it would be errornous at "9" and "99" on the way entering the entire number, because both steps are no primes.
