### ISSUE TITLE
Pluscode cannot be entered

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#576]
Q24G+6V (used by Google Maps)

**Comment by Birdy2404** [comment]
I faced the same problem before some days. In my point of view this can only be solved if the User is near the coordinate or we need to request the missing characters, which are shown in the adressbar in Google.

**Comment by Birdy2404** [comment]
Statement of google:
"Wenn Sie sich in der Stadt befinden, in der Sie suchen möchten, können Sie einfach den sechs- oder siebenstelligen Plus Code eingeben. Falls Sie beispielsweise in Dublin sind, können Sie direkt nach 8QQ7+V8 suchen."

But if youre searching for the following 2 pluscodes, you will find just one target in google, maybe because I have searched for it already and google knows what I want, before I know it?
R6CQ+WX Rastatt -> 8FWC R6CQ+WX
2C73+CQ Karlsruhe -> 8FXC 2C73+CQ
Even W in the pluscode of Rastatt and X in the code of Karlsruhe, it finds the two targets together.
So maybe there are some possibilities to enhance this topic. But I wouldn't label it as a bug.

**Comment by S-Man42** [comment]
Next problem: 8FVMV2VH+35H4 (although complete code... In multi decoder it works...)

**Comment by S-Man42** [comment]
Last comment was a bug, first, as described correctly, was not. It's an issue for "short form OLC", which requires a mapping from geographic areas to 4 characters, which currently is not supported.
