### ISSUE TITLE
Houdini Code

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#577]
Pray = 1 = A
Answer = 2 = B
Say = 3 = C
Now = 4 = D
Tell = 5 = E
Please = 6 = F
Speak = 7 = G
Quickly = 8 = H
Look = 9 = I
Be quick = 10 or 0 = J

http://gaffa.org/archives/1987-13/msg00093.html
https://webcache.googleusercontent.com/search?q=cache:tAUsl-OALBMJ:https://www.futilitycloset.com/2017/11/28/overdue-7/+&cd=4&hl=en&ct=clnk&gl=de&client=firefox-b-d
https://www.victorzammit.com/articles/houdinicode.htm

**Comment by S-Man42** [comment]
https://github.com/S-Man42/GCWizard/commit/36a0d3fb03e8480cd52d264bbdd09fda3bdf99fa

**Comment by t-m-z** [comment]
I think, it is not implemented correctly.
Rosabelle – answer – tell – pray – answer – look – tell – answer – answer – tell should be decoded to Rosabelle - B - E - L - I - E - V - E because letters beyond the 10th would be represented with two digits; for example, S, the 19th letter, could be indicated by 1 and 9, “Pray-Look.”
Fuirther on I would suggest to change 1-10 to Digits and A-J to Letters giving the user a hint, which kind of source is accepted

**Comment by S-Man42** [comment]
Do you have a source for this? How should one differ between pray - look and pray-look?

Your last sentence is not clear to me? What is better understandable with "Digits" than "1-10"?

**Comment by t-m-z** [comment]
The source is within the links you attached.

Regarding the second question - I have no clue how to differ these two cases.  However, if you cannot decode Houdinis last message the we should think about how to handle this tool.
In this case the mode 0-9 and A-J is valid.

From a users perspective it was on the first look not clear to me what you mean by 1-10 and A-J.
I played around and found out that you decode/encode digits or letters.

Sent from MailDroid

-----Original Message-----

**Comment by S-Man42** [comment]
Closed after bilateral phone call
