### ISSUE TITLE
Colord Codes and RAL

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#585]
Two suggestions:

1. Build a selection for color Codes with tthe two entries Colors and RAL Color.
2. Add an additional line to the color tool: if the hex-code proves, that the color is a RAL color then this should be told, too.

**Comment by S-Man42** [comment]
1. Yes I thought about it, was too lazy :D
2. Hm, i thought about it as well. However:
a) This is a too rare case. 200 (?) out of 16,8mio colors (in fact, much more values are possible because it's type double. based, not type integer) ... i don't know. 
b) How should this be done? If you had an RGB code that would fit to a RAL, what should exactly happen? Or a Hex? Your Output depends on thr chosen output format. Neither Hex output nor RGB nor any other is a valid place for RAL numbers. Because RAL is a completely different "format". You can either output RAL in every format if it is available, but that feels strange. Or you offer a new color format, which in nearly all input cases returns nothing...

I'd handle this as exception here, a different "encoding". It has nothing to do with normal color spaces. I believe we would yield many problems when we try to combine these tools. I wouldnt touch this... If someone really wants to convert RGB (or even worse: CMYK) to RAL or something, then he should send us a note :D

**Comment by S-Man42** [comment]
Closed after bilateral phone call
