### ISSUE TITLE
provide a REST-API for online decompiling the LUA-Bytecode from a Wherigo Cartridge

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#810]
https://lua-decompiler.ferib.dev/ or https://wigcrumbler.team-hildesheim.de/de_DE/ are using unluac.jar from https://sourceforge.net/projects/unluac/ which bases probably on https://github.com/HansWessels/unluac

Instead of transforming the 2000 lines of Java-Code from unluac it should be possible to provide a REST-API for online access from GCWizard to use this jar to decompile a LUAByteCode-File.

**Comment by S-Man42** [comment]
But then we are not offline anymore... Breaking a core principle. I am not quite happy with that. Isn't there an online converter from java to dart?

**Comment by t-m-z** [comment]
I know that. 
But up to now I did not find any converter.
And I think/believe no one will decompile a Wherigo on the fly in the field

In the meantime I will still try to translate the unluac.java package as plan A.
However, Plan B seems to be a valid option.

Sent from MailDroid

-----Original Message-----

**Comment by S-Man42** [comment]
I did this such work several. times before (Asteo, firsz coord things,...) Most work did such online converters as this one (or similar) https://sma.github.io/stuff/java2dartweb/java2dartweb.html

Afterwards you need to go through each line because of compiling errors, yes. But it's always worth it.

We have no time limits, we have enough time. 100 lines a day or something sounds feasible. No pressure. Isn't it possible? 

Maybe there's another option: Dart and Java are both JVM based. I heard of the a possibilty to JAR files directly. You could do some research on this.

I really don't like the idea with online action. And I personally disagree with you. Such tool is exactly in that moment interesting, when you are deep in the forest, your WIG is crashed (again) and you decide to go directly to the final. In that case you may not have any online connection and would celebrate such a tool.

**Comment by S-Man42** [comment]
At the first glance: JARs seem to be only supported for Android.

**Comment by t-m-z** [comment]
thanks for the hint - I will give it a try and improve my Java/Dart knowledge converting round about 100 files ...

Your point regarding a crash is valid. However, thinking about Puma66 he will do the analysis offline and go directly to the final. Why bothering with cartridges while there is a shortcut.
To be honest, there are a lot of lousy WIGs with little fun.

Sent from MailDroid

-----Original Message-----

**Comment by t-m-z** [comment]
I am not really surprised about that

Sent from MailDroid

-----Original Message-----

**Comment by t-m-z** [comment]
for most of the files of https://github.com/HansWessels/unluac/tree/master/src/unluac the tool at  https://sma.github.io/stuff/java2dartweb/java2dartweb.html does not work. It will last months to go through and which is much more important: the translate the code I should have an idea how the java code works. This will cost a lot of time to understand the LUA Byte code and how the decompiler works.

**Comment by t-m-z** [comment]
hm - I am still working on that. In the meantime I found another source written in C. I will check that.
I understand the concern regarding dependecies - but what's about implementing a REST-API in your Web-Server?

So a roadmap could be:
- Wherigo Viewer with the ability to
 + save the LUAByte code and give a hint how to decompile
 + read LUA Files and analyze the structure

Check LuaDec for the possibility to translate into Dart.

Sent from MailDroid

-----Original Message-----

**Comment by t-m-z** [comment]
Done

`String address = "http://sdklmfoqdd5qrtha.myfritz.net:7323/GCW_Unluac/";`
`    try {`
`      var uri = Uri.parse(address);`
`      var request = http.MultipartRequest("POST", uri)`
`        ..files.add(await http.MultipartFile.fromBytes("file", byteListLUA,`
`            contentType: MediaType("application", "octet-stream")));`
`      var response = await request.send();`

      _httpCode = response.statusCode.toString();
      _httpMessage = response.reasonPhrase;

      if (response.statusCode == 200) {
        var responseData = await http.Response.fromStream(response);
        _LUAFile = responseData.body;
      } else {
       ...
      }
    } catch (exception) {
      _httpCode = '503';
      _httpMessage = exception.toString();
     ...
    } 
``
