### ISSUE TITLE
Redscreen in Brainf!k

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#862]
The substition of Brainf!k derivates does not work properly.
Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook! Ook? Ook. Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook? Ook. Ook! Ook! Ook? Ook! Ook. Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook! Ook. Ook. Ook. Ook! Ook. Ook. Ook. Ook! Ook. Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook! Ook? Ook. Ook? Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook? Ook. Ook! Ook! Ook? Ook! Ook. Ook? Ook! Ook! Ook! Ook. Ook. Ook. Ook! Ook. Ook. Ook. Ook! Ook.
is substituted to
<+++++++++[>+++++++++Ook.>Ook.-]>+++++++Ook!+,+,>+++++++,Ook?>-------<-]>-Ook!+,+Ook..

**Comment by S-Man42** [comment]
![grafik](https://user-images.githubusercontent.com/16626063/148130032-21b43e82-2362-45e0-b59c-ee91b5c17675.png)

Original Ook works

**Comment by t-m-z** [comment]
yes. the problem ist the substitution in the brainfk-widget

**Comment by S-Man42** [comment]
Yes here is the problem:

https://github.com/S-Man42/GCWizard/blob/8529676e30a4465df525d1b2f90865b939233119/lib/widgets/tools/crypto_and_encodings/esoteric_programming_languages/brainfk.dart#L255

```
return interpretBrainfk(
              substitution(_currentText,
                  switchMapKeyValue(brainfkTrivialSubstitutions[BRAINFK_TRIVIAL_LIST[_currentSubstitition]])),
              input: _currentInput);
```

The usage of substitution is not useful here because of certain internal logics.

To correct usage of the a BF derivat is the usage of the class *BrainfkDerivat*
https://github.com/S-Man42/GCWizard/blob/2.2.0/lib/logic/tools/crypto_and_encodings/esoteric_programming_languages/brainfk_derivat.dart

There entire logic is already done ;) We had this topic today ;) Do not implement own code if such is already implemented. In that case for the original Ook function.

As you can see here:

https://github.com/S-Man42/GCWizard/blob/8529676e30a4465df525d1b2f90865b939233119/lib/logic/tools/crypto_and_encodings/esoteric_programming_languages/ook.dart#L3

The only code you need is:

```
final ook = BrainfkDerivat(
    pointerShiftLeftInstruction: '.?',
    pointerShiftRightInstruction: '?.',
    decreaseValueInstruction: '!!',
    increaseValueInstruction: '..',
    startLoopInstruction: '!?',
    endLoopInstruction: '?!',
    inputInstruction: '.!',
    outputInstruction: '!.');
```
And then call `ook.interpretBrainfkDerivat()`

Same for any other derivat like
```

var nak = BrainfkDerivat (
   pointerShiftLeftInstruction: 'Nak. Nak?',
   pointerShiftRightInstruction: 'Nak? Nak.',
   ...
}

nak.interpretBrainfkDerivat();
```

No further code required ;)

In the widget you can say:

```
final List<BrainfkDerivat> bfDerivats = [
   ook, nak, ...   //created above
];

BrainfkDerivat _currentDerivat = ....;

GCWDropDownButton (
   items: bfDerivats.map(...),
   onChanged: (value) {setState() {_currentDerivat = value}]
)

_calcOutput() {
   return _currentDerivat.interpreteBrainfkDerivat(_currentInput);
}
```

No more logic.

**Comment by S-Man42** [comment]
Furthermore, I believe, your Ook Mapping is incorrect. Shift Left and Shift Right are switched, if I looked correctly.

**Comment by S-Man42** [comment]
Please do careful refactoring. Please add tests (I didn't find tests for the derivats - maybe I just didn't see them. But tests would have helped to find the error earlier ;) ).

Idea for enhancement (if not implemented yet):
- Case unsensitive input: "OOK, ook, Ook", "Nak, NAK, nak"
- Support for reduced Ook (as the Ook tool already supports), meaning only the sentence characters '..!.?.'
